### ISSUE TITLE
A video with multiple audio tracks loses the audio when merged

### ISSUE THREAD

**Issue by mattio** [Datt1994/DPVideoMerger-Swift#12]
Hello! Thanks for this library!

I ran into a scenario where a video was being recorded with ReplayKit in custom fashion and it ended up having multiple audio tracks. When I merged that video with another, there was some audio loss. 

I believe I found the place in the code that assumed a single audio track and updated it to allow for multiple. I'll submit a PR for the change that worked in my scenario. Hope you find it useful enough to merge!

**Comment by Datt1994** [comment]
Hello @mattio,

Thanks for contribution
