### ISSUE TITLE
video in landscape becomes smaller size when viewing in landscape mode after merging

### ISSUE THREAD

**Issue by flyinglionSJ** [Datt1994/DPVideoMerger-Swift#4]
Hi team,

I tried to merging two videos: one in landscape and one in portrait mode.  After merging, the video in landscape becomes smaller size when viewing in landscape.
Please help!

Thanks,
Tony

**Comment by Datt1994** [comment]
Hi Tony,

You are using one in landscape and one in portrait mode right, so in current algorithm for merging ,First find Max width & hight from all video going to use for mirage so in your scenario Max width from landscape video and Max hight form portrait video so mirage video aspect ratio more so like square this is requested to display all mirage video properly.

**Comment by Datt1994** [comment]
Hi Tony,

You are using one in landscape and one in portrait mode right, so in current algorithm for merging ,First find Max width & height from all video going to use for merge so in your scenario Max width from landscape video and Max height form portrait video so merge video aspect ratio more so like square. This is requested to display all mirage video properly.

For output merged video need fix height and width. As far as I know can't change video height , width while playing video.


Thanks,
Datt
