### ISSUE TITLE
DPVideoMerger is not accessible. 

### ISSUE THREAD

**Issue by Nk-Official** [Datt1994/DPVideoMerger-Swift#5]
Make DPVideoMerger class and its functions public.

**Comment by Datt1994** [comment]
@Nk-Official Hi,

Can you check new release(1.5.7), I have done some changes.

**Comment by Nk-Official** [comment]
@Datt1994 Hello,

**Comment by Nk-Official** [comment]
@Datt1994 Hello,

**Comment by Nk-Official** [comment]
@Datt1994 Hello,

Now it is working fine.
Thanks
