### ISSUE TITLE
How to arranged merged video in center position?

### ISSUE THREAD

**Issue by iosNil** [Datt1994/DPVideoMerger-Swift#6]
right now i am doing merged 2 video side by side using gridMergeVideos function, and it's almost worked but  video top position is 0.  how to fix this issue ? . here is my attach screenshot which is display two merged videos into one video. you can see in screenshot video top is start with 0 , how can i arranged merged video in center position ?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-28 at 17 20 40](https://user-images.githubusercontent.com/25813055/88664826-4c147800-d0fb-11ea-966b-a7454d89825b.png)

any help is appreciated

**Comment by Datt1994** [comment]
@iosNil hi,

Please check new release(1.5.8), I have added new function `parallelMergeVideos` using this you can easily achieve this merged 2 video side by side. Not only 2 video but you can merged more than 2 video side by side. Check out if you have any feedback feel free to comment on it.

Thanks,
Datt

**Comment by iosNil** [comment]
@Datt1994 Hi,

Many thanks Man , you saved my days, sorry for late reply ,i did checked and  it's worked as i expected. now i am adding audio to the merged video.
