### ISSUE TITLE
Eternal Audio Merge

### ISSUE THREAD

**Issue by varunsidpara** [Datt1994/DPVideoMerger-Swift#7]
Thank you very much for your amazing work.

I am merging external audio with parallel 2 videos. I can't able to add external audio in merging result video. Can you please guide me, How can  i add external audio in merging result video. I am currently using `parallelMergeVideos` method.

Any help appreciated.

**Comment by Datt1994** [comment]
hi @varunsidpara,

Please check new release(1.5.9).
I have added new parameter `audioFileURL`  in `parallelMergeVideos` function, Now you can add external audio in result video.
If you find this repo useful, Please consider to add star so reach to more people.

Thank,
Datt
