### ISSUE TITLE
Wrong orientation on parallel and grid merge

### ISSUE THREAD

**Issue by Jarutais** [Datt1994/DPVideoMerger-Swift#8]
When I call the Parallel or Grid merge methods passing videos recorded with my device's camera (iPhone 11 Pro), the resulting video shows the footage with wrong orientation.

For example: 2 portrait videos show rotated in landscape

<img width="681" alt="Captura de Tela 2020-08-25 às 15 20 58" src="https://user-images.githubusercontent.com/67167374/91212797-15745200-e6e7-11ea-8125-bbb925f231eb.png">

It only happens with videos recorded with the device's camera. Videos from the web appear in the correct orientation.

**Comment by Zulqurnain24** [comment]
@Datt1994 I am experiencing the same problem please advice on how to fix this.

**Comment by Datt1994** [comment]
Hi @Jarutais & @Zulqurnain24,

Please check new release(1.5.10), I have added orientation logic for parallel & grid merge.

Thanks,
Datt
